import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="px-10 py-6">
          <nav className="w-full bg-white h-16 rounded-2xl border border-black border-b-8 border-r-4">

          </nav>
        </header>
        {children}
        </body>
    </html>
  );
}
